import "@/styles/globals.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-[#c0c0c0] min-h-[100vh] min-w-full flex items-center">{children}</body>
    </html>
  )
}
