import "@/styles/globals.css";

import { Inter } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import { Navbar } from "./_components/Navbar/Navbar";


export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-[100vh] min-w-full flex flex-col gap-7 bg-[#c0c0c0]">
        <TRPCReactProvider>
          <header className="sm:px-4 md:pt-10 lg:mx-20">
            <Navbar />
          </header>
          {children}
        </TRPCReactProvider>
      </body>
    </html>
  );
}
