import "@/styles/globals.css";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
      <body className="flex min-h-[100vh] min-w-full flex-col gap-7 bg-[#c0c0c0]">
        {children}
      </body>
    </html>
  );
}
